name: Update VMess

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python fetch_vmess.py
        env:
          DEVICE_TOKEN: ${{ secrets.DEVICE_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
